// Generated by Qodo Gen

const { isValidPath } = require('../src/source-processor');

describe('isValidPath', () => {

    // Invalid file path with disallowed special characters returns false
    it('should return false for path with invalid special characters', () => {
      const fs = require('fs');
      const path = require('path');

      const baseDir = '/base/dir';
      const filePath = '/base/dir/invalid$path*';

      const result = isValidPath(filePath, baseDir);

      expect(result).toBe(false);
    });
});
